version: '3.4'

services:

##########################
#  APPLICATION GATEWAY   #
##########################
  gateway:
    image: traefik:latest
    container_name: api-gateway
    restart: always
    command: --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./docker/gateway/traefik.yml:/etc/traefik/traefik.yml"
      - "./docker/gateway/dynamic/:/etc/traefik/traefik.d/"
    networks:
      - exposed

##########################
#    BUSINESS SERVICE    #
##########################
  # front:
  #   networks:
  #     - exposed
  #     - internal

  # user:
  #   networks:
  #     - exposed
  #     - internal

  travel:
    build:
      context: ./travel
      dockerfile: MicroService.Travel.WebApi/Dockerfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=6EQUJ5wow
      - MONGO_INITDB_DATABASE=travel
      - MONGO_INITDB_HOST=travel-bdd
    depends_on:
      - travel-bdd
    networks:
      - exposed
      - internal
      - travel-data

  image:
    build:
      context: ./image
      dockerfile: MicroService.Image.WebApi/Dockerfile
    environment:
      - StorageType=AMAZON
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=6EQUJ5wow
      - MONGO_INITDB_DATABASE=image
      - MONGO_INITDB_HOST=image-bdd
    depends_on:
      - travel-bdd
    networks:
      - exposed
      - internal
      - image-data

  like:
    build:
      context: ./like
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - like-bdd
    networks:
      - internal
      - like-data

#################
#    DATABASE   #
#################

  like-bdd:
    image: redis:6.0-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - like-data

  travel-bdd:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: 6EQUJ5wow
        MONGO_INITDB_DATABASE: travel
    networks:
        - travel-data

  image-bdd:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: 6EQUJ5wow
        MONGO_INITDB_DATABASE: image
    networks:
        - image-data

#################
#    NETWORK    #
#################
networks:
  exposed:
    name: exposed
    driver: bridge
  internal:
    name: internal
    driver: bridge
  user-data:
    name: user-data
    driver: bridge
  image-data:
    name: image-data
    driver: bridge
  like-data:
    name: like-data
    driver: bridge
  travel-data:
    name: travel-data
    driver: bridge
